name = "Duff"
uuid = "3e2ffa6a-ba38-11e8-0a1c-7b69309e1c72"
authors = ["pevnak <pevnak@gmail.com>"]
version = "0.4.0"

[deps]
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
